- hosts: docker
  sudo: yes
  roles:
  - role: common
    vars:
      role_step: alloc_part.yml
      alloc_dev: "{{boots_roles.docker[inventory_hostname].devs}}"

- hosts: harbor
  sudo: yes
  roles:
  - role: common
    vars:
      role_step: alloc_part.yml
      alloc_dev: "{{boots_roles.harbor[inventory_hostname].devs}}"

- hosts: operator
  sudo: yes
  roles:
  - role: common
    vars:
      role_step: alloc_part.yml
      alloc_dev: ["{{boots_roles.operator[inventory_hostname].devs}}"]

- hosts: devops
  sudo: yes
  roles:
  - role: common
    vars:
      role_step: alloc_part.yml
      alloc_dev: "{{boots_roles.devops[inventory_hostname].devs}}"

- hosts: es_master
  sudo: yes
  roles:
  - role: common
    vars:
      role_step: alloc_part.yml
      alloc_dev: ["{{boots_roles.es_master[inventory_hostname].devs}}"]

- hosts: es_data
  sudo: yes
  roles:
  - role: common
    vars:
      role_step: alloc_part.yml
      alloc_dev: ["{{boots_roles.es_data[inventory_hostname].devs}}"]