---
- hosts: localhost
  sudo: yes
  vars:
    # 控制机主机相关变量
    control_ip: "{{boots_global.SYSTEM_CONTROL_IP}}"
    username: "{{boots_global.USERNAME}}"
    work_dir: "{{boots_global.WORK_DIR}}"
    work_dir_ansible: "{{boots_global.WORK_DIR_ANSIBLE}}"
    harbor_work_dir: "{{work_dir}}/harbor_data"
  roles:
  - role: deploy
    vars:
      role_step: install_center.yml
      local_env: true
      bcos_path: "{{work_dir}}/data/sql"
      # mysql 服务相关变量
      mysql_flag: "{{boots_global.COMPOSE_MYSQL_INSTALL_FLAG|bool}}"
      mysql_user: "{{boots_global.COMPOSE_MYSQL_USERNAME}}"
      mysql_password: "{{boots_global.COMPOSE_MYSQL_PASSWORD}}"
      mysql_ip: "{{boots_global.COMPOSE_MYSQL_IP}}"
      mysql_port: "{{boots_global.PORT_MYSQL}}"
      mysql_db_boots: "boots"
      #tomcat 端口相关变量
      boots_http_port: "{{boots_global.PORT_BOOTS_HTTP}}"
      log_level: "{{boots_global.SYSTEM_LOG_LEVEL}}"
  - role: docker
    vars:
      role_step: clean_docker.yml
  - role: docker
    vars:
      role_step: install_docker.yml
      mount_path: /var/lib/docker
  - role: harbor
    vars:
      role_step: install_harbor.yml
      harbor_dns: "harbor.center.com"
      harbor_ip: "{{control_ip}}"
      http_ports: "8889"
      https_ports: "8443"
      notary_ports: "4443"
      log_ports: "1514"
      harbor_admin_password: "Harbor12345"
  - role: docker
    vars:
      role_step: cert_docker.yml
      harbor:
        ip: "{{control_ip}}"
        dns: "harbor.center.com"
      cert_dir: "/etc/docker/certs.d/harbor.center.com:8443"
      cert_src: "{{harbor_work_dir}}/data/cert/server.crt"