---
###### 模块配置说明 ######
###### 模块配置说明 ######
#  角色名称:  etcd角色，角色状态： 已分配状态
#

# 安装 etcd
- hosts: etcd
  sudo: yes
  vars_files:
  - images.yaml
  roles:
  - role: etcd
    vars:
      role_step: install_etcd.yml
      etcd_peer_port: "{{boots_global.PORT_ETCD_PEER}}"
      etcd_client_port: "{{boots_global.PORT_ETCD_CLIENT}}"
      etcd_cluster_state: new
      etcd_mount_path: "/var/lib/etcd"
    when: not (boots_global.COMPOSE_K8S_INSTALL_FLAG|bool)

- hosts: etcd
  tasks:
  - name: 保存etcd角色信息
    vars:
      ansible_roles: {id: "{{boots_roles.etcd[inventory_hostname].roleId}}", status: "2"}
    shell: "curl -X POST -H 'code: {{boots_global.SYSTEM_ENV_CODE}}' {{boots_global.SYSTEM_CALLBACK_URL}}/role?hostRole={{ansible_roles|to_json|urlencode}}"

- hosts: localhost
  tasks:
  - name: 保存master全局信息
    vars:
      ansible_global:
        COMPOSE_ETCD_IP: "{{groups.etcd[0]}}"
        COMPOSE_ETCD_LINKED: "{{groups.etcd|map('extract',hostvars,'etcd_client_url')|list|join(',')}}"
    shell: "curl -X POST -H 'code: {{boots_global.SYSTEM_ENV_CODE}}' {{boots_global.SYSTEM_CALLBACK_URL}}/global?global={{ansible_global|to_json|urlencode}}"
    when: groups.etcd|count >0
