- hosts: master:node
  sudo: yes
  roles:
  - role: k8s
    vars:
      role_step: stop.yml

- hosts: harbor
  sudo: yes
  roles:
  - role: harbor
    vars:
      role_step: stop.yml

- hosts: docker
  sudo: yes
  roles:
  - role: docker
    vars:
      role_step: stop.yml

- hosts: ceph_rgw
  sudo: yes
  roles:
  - role: ceph
    vars:
      role_step: stop-rgw.yml

- hosts: ceph_msd
  sudo: yes
  roles:
  - role: ceph
    vars:
      role_step: stop-mds.yml

- hosts: ceph_osd
  sudo: yes
  roles:
  - role: ceph
    vars:
      role_step: stop-osd.yml

- hosts: ceph_mon
  sudo: yes
  roles:
  - role: ceph
    vars:
      role_step: stop-mon.yml

- hosts: es_master:es_data
  sudo: yes
  roles:
  - role: es
    vars:
      role_step: stop.yml