- hosts: hadoop
  sudo: yes
  tasks:
  - name: 创建文件夹
    shell: mkdir -p /home/deployer/pack

  - name: copy jdk.tar.gz py.tar.gz
    copy: src=/bcos/datascience/roles/hadoop/files/beh_ansible/software/{{item}} dest=/home/deployer/pack/{{item}} mode=0644
    with_items:
    - jdk.tar.gz
    - py.tar.gz
  
  - name: 解压
    args:
      chdir: "/home/deployer/pack/"
    shell: tar -xzvf {{item}} 
    with_items:
    - jdk.tar.gz
    - py.tar.gz
  
  - name: 赋权
    args:
      chdir: "/home/deployer/pack/"
    shell: chmod -R 755 ./

  - name: cron 注释掉定时任务
    cron: 
      user: admin
      job: sh /export/servers/jcollector/bin/jcollectorStart.sh 2 >> /export/Logs/loghub.360buy.com/jcollector/crontab.log 2>&1 &
      disabled: yes
      backup: yes

  - name: 设置sudo免密
    lineinfile: name=/etc/sudoers line="admin ALL=(ALL) NOPASSWD:ALL" regexp="^admin" backrefs=yes

  - name: 设置requiretty
    lineinfile: name=/etc/sudoers line="#Defaults requiretty" regexp="^Defaults.*requiretty.*$" backrefs=yes