---
- hosts: devops
  sudo: yes
  vars_files:
  - upgrade
  - images.yaml
  roles:
  - role: deploy
    vars:
      role_step: upgrade_devops.yml
      work_dir: "{{boots_global.SYSTEM_WORK_DIR}}"
      mount_path: /bcos_mnt/devops_data
      devops:
        package: "{{work_dir}}/package/bcos-admin/roles/deploy/files/devops"
      jenkins_port: "{{boots_global.PORT_JENKINS}}"
      sonar_port: "{{boots_global.PORT_SONAR}}"
      sonar_endpoint: http://{{inventory_hostname}}:{{sonar_port}}
      script_list:
        - bonc-start-postgresql.sh {{mount_path}}/devops {{harbor.dns}}:{{harbor.port}}/{{images.devops.postgres}} pro
        - bonc-start-devops.sh {{jenkins_port}} {{mount_path}}/devops {{harbor.dns}}:{{harbor.port}}/{{images.devops.devops}} pro {{harbor.dns}} {{harbor.ip}}
        - bonc-start-sonar.sh {{sonar_port}} {{mount_path}}/devops {{harbor.dns}}:{{harbor.port}}/{{images.devops.sonarqube}} pro
    when: upgrade.devops

- hosts: master[0]
  sudo: yes
  vars_files:
  - upgrade
  - images.yaml
  roles:
  - role: bcos
    vars:
      role_step: upgrade.yml
      conf_path: "{{boots_global.SYSTEM_WORK_DIR}}/data/logkitconfs"
      work_dir: "{{boots_global.SYSTEM_WORK_DIR}}"
      work_name: "bcos-admin"
      cur_tag: "{{boots_global.SYSTEM_CUR_VERSION}}"
      target_tag: "{{boots_global.SYSTEM_TARGET_VERSION}}"
      data_path: "{{work_dir}}/data"
      package_dir: "package"
      bcos_yaml_path: "{{work_dir}}/data/yaml"
      bcos_sql_path: "{{work_dir}}/data/sql"
      admin:
        package: "{{work_dir}}/{{work_name}}"
        path: "{{work_dir}}"
        target: "{{work_dir}}/{{package_dir}}"
      harbor:
        ip: "{{boots_global.COMPOSE_HARBOR_IP}}"
        dns: "{{(boots_global.COMPOSE_HARBOR_DNS=='')|ternary(boots_global.COMPOSE_HARBOR_IP,boots_global.COMPOSE_HARBOR_DNS)}}"
        port: "{{boots_global.PORT_HARBOR_HTTPS}}"
  
  post_tasks:
  - name: 保存global信息
    vars:
      ansible_global:
        SYSTEM_CUR_VERSION: "{{target_tag}}"
    shell: "curl -X POST -H 'code: {{boots_global.SYSTEM_ENV_CODE}}' {{boots_global.SYSTEM_CALLBACK_URL}}/global?global={{ansible_global|to_json|urlencode}}"

  - name: 提交tag数据
    shell: "curl -X POST -H 'code: {{boots_global.SYSTEM_ENV_CODE}}' {{boots_global.SYSTEM_CALLBACK_URL}}/env?tag={{target_tag}}"