kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lvm-operator
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - bonc.com
  resources:
  - "*"
  verbs:
  - "*"
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lvm-operator

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lvm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lvm-operator
subjects:
- kind: ServiceAccount
  name: lvm-operator
  namespace: {{operator_ns}}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: lvm-operator
spec:
  template:
    metadata:
      labels:
        app: lvm-operator
    spec:
      serviceAccountName: lvm-operator
      containers:
      - name: lvm-operator
        image: {{harbor.dns}}:{{harbor.port}}/{{images.operator.lvm_operator}}
        imagePullPolicy: Always
        securityContext:
            privileged: true
        volumeMounts:
        - mountPath: /run/lvm/
          name: socket
        - mountPath: /dev
          name: dev
        - mountPath: /var/lib/kubelet/plugins/kubernetes.io/flexvolume/sysoperator.pl/lvm/mounts
          name: var
        - mountPath: /usr
          name: usr
        - mountPath: /lib64
          name: lib64
        - mountPath: /bin
          name: bin
        - mountPath: /sbin
          name: sbin
        env:
        - name: VGMONITOR_INTERVAL
          value: "60"
        - name: LVMONITOR_INTERVAL
          value: "60"
        - name: LVM_VGNAME
          value: operatorvg
        - name: MY_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
      volumes:
      - name: socket
        hostPath:
          path: /run/lvm/
      - name: dev
        hostPath:
          path: /dev
      - name: usr
        hostPath:
          path: /usr
      - name: var
        hostPath:
          path: /var/lib/kubelet/plugins/kubernetes.io/flexvolume/sysoperator.pl/lvm/mounts
      - name: lib64
        hostPath:
          path: /lib64
      - name: bin
        hostPath:
          path: /bin
      - name: sbin
        hostPath:
          path: /sbin
