apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: memcached-operator
  labels:
    app: memcached-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached-operator
  template:
    metadata:
      labels:
        app: memcached-operator
    spec:
      serviceAccountName: memcached-operator
      containers:
      - name: memcached-operator
        image: {{harbor.dns}}:{{harbor.port}}/{{images.operator.memcached_operator}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memcached-operator

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: memcached-operator
rules:
- apiGroups:
  - memcached.bonc.com
  resources:
  - memcacheds
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: memcached-operator
subjects:
- kind: ServiceAccount
  name: memcached-operator
  namespace: {{operator_ns}}
roleRef:
  kind: ClusterRole
  name: memcached-operator
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: memcached-operator
rules:
- apiGroups:
  - redis.bonc.com
  resources:
  - codisclusters
  - redises
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  - secrets
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: memcached-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: memcached-operator
subjects:
- kind: ServiceAccount
  name: memcached-operator
  namespace: {{operator_ns}}
