kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zk-operator
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - zk.bonc.com
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zk-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zk-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zk-operator
subjects:
- kind: ServiceAccount
  name: zk-operator
  namespace: {{operator_ns}}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zk-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk-operator
    spec:
      serviceAccountName: zk-operator
      containers:
      - name: zk-operator
        image: {{harbor.dns}}:{{harbor.port}}/{{images.operator.zk_operator}}
        imagePullPolicy: Always