- name: 备份证书文件
  shell: cp -r "{{k8s_path}}" "{{k8s_path}}_bak"

- name: copy生成的文件到其他的master机器上
  copy: src="{{k8s_path}}/" dest="{{k8s_path}}" mode=0644

- name: 赋予普通用户操作权限（kubectl）
  shell: chmod 777 {{k8s_path}}/admin.conf

- name: 查找需要删除的kubelet文件
  find:
      paths: /var/lib/kubelet/pki
      patterns: kube*
  register: files_to_delete

- name: 删除kubelet的客户端的证书文件
  file: path="{{item.path}}" state=absent
  with_items: "{{files_to_delete.files}}"

- name: 重启kubelet
  service: name=kubelet state=restarted
