# serviceSubnet:  类似10.244.0.0/16

- name: 安装kubernates 此过程时间较长，请耐心等待...
  vars:
    packages:
    - kubelet-{{version.k8s}}
    - kubeadm-{{version.k8s}}
    - kubectl-{{version.k8s}}
  yum: name={{packages}}

- name: kubelet系统相关设置
  shell: |
    sysctl -w net.bridge.bridge-nf-call-iptables=1
    modprobe ip_vs && modprobe ip_vs_wrr && modprobe ip_vs_sh && modprobe  ip_vs_rr && modprobe nf_conntrack_ipv4 && modprobe nf_conntrack
    swapoff -a

- include: start.yml