# service_subnet:  类似10.244.0.0/16

- name: 备份k8s 配置目录
  shell: cp -r /etc/kubernetes /etc/kubernetes_{{k8s_version.stdout}}

- name: 升级k8s 版本
  shell: yum upgrade -y kubeadm-{{version.k8s}} kubernetes-cni kubectl-{{version.k8s}} kubelet-{{version.k8s}}

- name: kubelet依赖
  shell: |
    sysctl -w net.bridge.bridge-nf-call-iptables=1
    modprobe ip_vs && modprobe ip_vs_wrr && modprobe ip_vs_sh && modprobe  ip_vs_rr && modprobe nf_conntrack_ipv4 && modprobe nf_conntrack
    swapoff -a

- name: 查询docker cgroup
  shell: docker info | grep Cgroup | awk '{print $3}'
  register: cgroup_driver

- name: 修改kubelet主配置文件
  template: src=kubelet-kubeadm-1.14.conf dest=/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: 加载kubelet 配置文件
  shell: systemctl daemon-reload

- name: 启动kubelet服务
  service: name=kubelet state=restarted enabled=yes

- name: 获取hostname
  shell: hostname
  register: hostname

- name: 等待节点状态ready
  shell: source /etc/profile;kubectl get no -owide | grep {{hostname.stdout|lower}}
  delegate_to: "{{groups.master[0]}}"
  register: result
  until: result.stdout.find("Ready") != -1
  retries: 60
  delay: 10

- name: 打印节点状态
  debug: msg={{result}}