/*
Navicat MySQL Data Transfer

Source Server         : 172.16.3.25
Source Server Version : 50544
Source Host           : 172.16.3.25:3306
Source Database       : bdos_dev

Target Server Type    : MYSQL
Target Server Version : 50544
File Encoding         : 65001

Date: 2019-08-16 11:25:21
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- 新增：Table structure for bdos_dockerfile_type
-- ----------------------------
DROP TABLE IF EXISTS `bdos_dockerfile_type`;
CREATE TABLE `bdos_dockerfile_type` (
  `id` varchar(255) NOT NULL,
  `create_time` datetime DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `type_name` varchar(255) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of bdos_dockerfile_type
-- ----------------------------
INSERT INTO `bdos_dockerfile_type` (`id`, `create_time`, `description`, `type_name`, `update_time`) VALUES ('1', '2019-07-24 15:26:08', 'tomcat', 'tomcat', '2019-07-24 15:26:41');

-- ----------------------------
-- 修改：bdos_dockerfile_template表，新增字段type_id关联bdos_dockerfile_type表
-- ----------------------------
alter table `bdos_dockerfile_template` add `type_id` VARCHAR(100) default null;

update `bdos_dockerfile_template` set `type_id`='1';
update `bdos_dockerfile_template` set `dockerfile_content`='FROM ${baseImageUrl}/tomcat:8.5.38\r\nARG  warname=${fileName}\r\nWORKDIR  /usr/local/tomcat/webapps/\r\nCOPY ${filePath} /tmp\r\nRUN warpath=$(echo $warname | cut -d \".\" -f 1) && mkdir -p ${warpath} && cp /tmp/$warname ${warpath} && cd ${warpath}/ && jar -xvf ${warname} && rm -f ${warname}\r\nCMD [\"catalina.sh\", \"run\"]' where `id`='123456';
update `bdos_dockerfile_template` set `dockerfile_content`='FROM ${baseImageUrl}/tomcat:8.5.38\r\nCOPY ${filePath} /usr/local/tomcat/webapps/\r\nCMD [\"catalina.sh\", \"run\"]' where `id`='2c90839f69992bd201699933096e0003';
update `bdos_dockerfile_template` set `dockerfile_content`='FROM ${baseImageUrl}/tomcat:8-jre8\r\nCOPY ${filePath} /usr/local/tomcat/webapps/\r\nCMD [\"catalina.sh\", \"run\"]' where `id`='2c90839f69992bd201699933096e0004';

-- ----------------------------
-- 修改：Records of sys_cluster_info,新增配置数据
-- ----------------------------
INSERT INTO `sys_cluster_info` (`cfg_key`, `cfg_type`, `cfg_value`, `memo`) VALUES('DEVOPS_GLOBAL_CONFIGURE_NODEJS', '1', 'node-v10.15.3,node-v8.11.1,node-v9.11.1', 'DEVOPS NODEJS配置');
INSERT INTO `sys_cluster_info` (`cfg_key`, `cfg_type`, `cfg_value`, `memo`) VALUES('DEVOPS_GLOBAL_CONFIGURE_GRADLE', '1', 'gradle-5.6', 'DEVOPS GRADLE配置');
INSERT INTO `sys_cluster_info` (`cfg_key`, `cfg_type`, `cfg_value`, `memo`) VALUES('DEVOPS_GLOBAL_CONFIGURE_PHP', '1', 'php-7.1.20,php-7.0.31,php-7.2.8', 'DEVOPS PHP配置');
INSERT INTO `sys_cluster_info` (`cfg_key`, `cfg_type`, `cfg_value`, `memo`) VALUES('DEVOPS_GLOBAL_CONFIGURE_PYTHON', '1', 'Python-2.7.14,Python-3.6.4', 'DEVOPS PYTHON配置');
update `sys_cluster_info` set `cfg_value`='true' where `cfg_key`='COMPONENT_SCHEDULER_LVM';

-- ----------------------------
-- 修改：Records of bdos_stateful_service,修改表字段类型
-- ----------------------------
alter table bdos_stateful_service MODIFY  extended_field text;
alter table bdos_stateful_service MODIFY  config_updated text;

-- ----------------------------
-- 修改：Records of bdos_stateful_service_unit_version,新增数据云、数据治理、数据云版数据治理镜像版本
-- ----------------------------
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('46', 'mysql', null, null, '46', 'data-governance-v4.1', '{{harbor.dns}}:{{harbor.port}}/library/data-governance-mysql:v4.1');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('47', 'mysql', 'exporter', null, '47', 'data-governance-v4.1', '{{harbor.dns}}:{{harbor.port}}/library/mysqld-exporter:latest');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('48', 'mysql', 'backup', null, '48', 'data-governance-v4.1', '{{harbor.dns}}:{{harbor.port}}/library/bdos_mysql_backup:1.0.5_v24');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('49', 'mysql', 'phpmyadmin', null, '49', 'data-governance-v4.1', '{{harbor.dns}}:{{harbor.port}}/library/phpmyadmin:latest');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('50', 'mysql', null, '', '50', 'data-cloud-v1.0', '{{harbor.dns}}:{{harbor.port}}/library/data-cloud-mysql:v1.0');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('51', 'mysql', 'exporter', '', '51', 'data-cloud-v1.0', '{{harbor.dns}}:{{harbor.port}}/library/mysqld-exporter:latest');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('52', 'mysql', 'backup', '', '52', 'data-cloud-v1.0', '{{harbor.dns}}:{{harbor.port}}/library/bdos_mysql_backup:1.0.5_v24');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('53', 'mysql', 'phpmyadmin', '', '53', 'data-cloud-v1.0', '{{harbor.dns}}:{{harbor.port}}/library/phpmyadmin:latest');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('54', 'mysql', null, '', '54', 'data-governance-cloud-v1.0', '{{harbor.dns}}:{{harbor.port}}/library/data-governance-cloud-mysql:v1.0');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('55', 'mysql', 'exporter', '', '55', 'data-governance-cloud-v1.0', '{{harbor.dns}}:{{harbor.port}}/library/mysqld-exporter:latest');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('56', 'mysql', 'backup', '', '56', 'data-governance-cloud-v1.0', '{{harbor.dns}}:{{harbor.port}}/library/bdos_mysql_backup:1.0.5_v24');
INSERT INTO `bdos_stateful_service_unit_version` (`id`,`app_type`,`extended_field`,`remark`,`sort`,`version`,`version_path`) VALUES ('57', 'mysql', 'phpmyadmin', '', '57', 'data-governance-cloud-v1.0', '{{harbor.dns}}:{{harbor.port}}/library/phpmyadmin:latest');


-- ----------------------------
-- 修改：Records of bdos_stateful_service_component_default_config，新增数据云、数据治理、数据云版数据治理配置参数
-- ----------------------------
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5200', 'mysql', 'my.cnf', '32', 'mysqld', 'text', 'binlog_cache_size', '开启log-bin时，为每个客户端分配的二进制日志缓存大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '1', '5200', 'K', 'K', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5201', 'mysql', 'my.cnf', '16', 'mysqld', 'text', 'innodb_log_buffer_size', '缓冲日志数据的缓冲区的大小', 'NULL', '1', '^([1-9]|[1-9]\\d{1,2}|[1-3]\\d{3}|40[0-8]\\d|409[0-6])$', '请输入1到4096之间的整数', '请输入1到4096之间的整数', '2', '5201', 'M', 'M', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5202', 'mysql', 'my.cnf', '48', 'mysqld', 'text', 'innodb_log_file_size', '日志组中每个日志文件的大小', 'NULL', '1', '^([4-9]|[1-9]\\d+)$', '请输入4到262144之间的整数', '请输入4到262144之间的整数', '2', '5202', 'M', 'M', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5203', 'mysql', 'my.cnf', '2', 'mysqld', 'text', 'innodb_log_files_in_group', '日志组文件个数', 'NULL', '0', '^[2-9]$|^[1-9]\\d$|^100$', '请输入2到100之间的整数', '请输入2到100之间的整数', '1', '5203', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5204', 'mysql', 'my.cnf', '50', 'mysqld', 'text', 'innodb_lock_wait_timeout', 'innodb行锁锁定等待超时', 'NULL', '1', '^([1-9]\\d{0,8}|10[0-6]\\d{0,7}|107[0-2]\\d{0,6}|1073[0-6]\\d{0,5}|1073700000)$', '请输入1到1073700000之间的整数', '请输入1到1073700000之间的整数', '2', '5204', 'NULL', '秒', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5205', 'mysql', 'my.cnf', '100', 'mysqld', 'text', 'max_connect_errors', '每个客户端连接最大的错误允许数量', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5205', 'NULL', 'B', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5206', 'mysql', 'my.cnf', 'InnoDB', 'mysqld', 'radio', 'default_tmp_storage_engine', '临时表的默认存储引擎', '{\"InnoDB\":\"InnoDB\",\"MyISAM\":\"MyISAM\",\"MRG_MYISAM\":\"MRG_MYISAM\",\"MEMORY\":\"MEMORY\",\"BLACKHOLE\":\"BLACKHOLE\",\"CSV\":\"CSV\",\"ARCHIVE\":\"ARCHIVE\",\"PERFORMANCE_SCHEMA\":\"PERFORMANCE_SCHEMA\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5206', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5207', 'mysql', 'my.cnf', 'InnoDB', 'mysqld', 'radio', 'default_storage_engine', '永久表的默认存储引擎', '{\"InnoDB\":\"InnoDB\",\"MyISAM\":\"MyISAM\",\"MRG_MYISAM\":\"MRG_MYISAM\",\"MEMORY\":\"MEMORY\",\"BLACKHOLE\":\"BLACKHOLE\",\"CSV\":\"CSV\",\"ARCHIVE\":\"ARCHIVE\",\"PERFORMANCE_SCHEMA\":\"PERFORMANCE_SCHEMA\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5207', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5208', 'mysql', 'my.cnf', 'binary', 'mysqld', 'text', 'character_set_filesystem', '数据库文件系统字符集', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5208', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5209', 'mysql', 'my.cnf', 'MIXED', 'mysqld', 'radio', 'binlog_format', 'MySQL的复制方式', '{\"ROW\":\"ROW\",\"STATEMENT\":\"STATEMENT\",\"MIXED\":\"MIXED\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5209', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5210', 'mysql', 'my.cnf', 'utf8_general_ci', 'mysqld', 'text', 'collation-server', '服务器默认排序规则', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5210', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5211', 'mysql', 'my.cnf', 'utf8', 'client', 'text', 'default-character-set', 'MySQL数据库默认字符集', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5211', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5212', 'mysql', 'my.cnf', '-1', 'mysqld', 'text', 'thread_cache_size', '线程缓存区大小', 'NULL', '1', '^(-1|0|[1-9]\\d{0,3}|1[0-5]\\d{1,3}|16[0-2]\\d{0,2}|163[0-7]\\d|1638[0-4])$', '请输入-1到16384的整数', '请输入-1到16384的整数', '1', '5212', 'NULL', 'B', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5250', 'mysql', 'my.cnf', '32', 'mysqld', 'text', 'binlog_cache_size', '开启log-bin时，为每个客户端分配的二进制日志缓存大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '1', '5250', 'K', 'K', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5214', 'mysql', 'my.cnf', '16', 'mysqld', 'text', 'tmp_table_size', '临时表使用缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5214', 'M', 'M', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5215', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'sort_buffer_size', '排序使用的缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5215', 'M', 'M', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5216', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'read_buffer_size', '读入缓冲区', 'NULL', '1', '^([1-9]|[1-9]\\d{1,2}|1\\d{3}|20[0-3]\\d|204[0-7])$', '请输入1到2047之间的整数', '请输入1到2047之间的整数', '2', '5216', 'M', 'M', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5217', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'join_buffer_size', '表关联使用的缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5217', 'M', 'M', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5218', 'mysql', 'my.cnf', '1024', 'mysqld', 'text', 'max_connections', '最大连接数', 'NULL', '0', '^(?:(?!0{1,5})\\d{1,5}|10{5})$', '请输入1到100000之间的整数', '请输入1到100000之间的整数', '1', '5218', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5219', 'mysql', 'my.cnf', '2', 'mysqld', 'text', 'table_open_cache', '所有线程打开表的数量', 'NULL', '1', '^([1-9][\\d]{0,1}|[1-4]\\d{2}|50\\d|51[0-2])$', '请输入1到512之间的整数', '请输入1到512之间的整数', '2', '5219', 'K', 'K', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5220', 'mysql', 'my.cnf', '128', 'mysqld', 'text', 'innodb_buffer_pool_size', '缓冲池字节大小', 'NULL', '1', '^([5-9]|[1-9]\\d{1,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入5到17592000000000之间的整数', '请输入5到17592000000000之间的整数', '1', '5220', 'M', 'M', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5221', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'innodb_buffer_pool_instances', 'InnoDB缓冲池划分的区域数量', 'NULL', '0', '^([1-9]|[1-5][0-9]|6[0-4])$', '请输入1到64之间的整数', '请输入1到64之间的整数', '2', '5221', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5222', 'mysql', 'my.cnf', 'READ-COMMITTED', 'mysqld', 'radio', 'transaction-isolation', '事物隔离级别', '{\"READ-UNCOMMITTED\":\"READ-UNCOMMITTED\",\"READ-COMMITTED\":\"READ-COMMITTED\",\"REPEATABLE-READ\":\"REPEATABLE-READ\",\"SERIALIZABLE\":\"SERIALIZABLE\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5222', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5223', 'mysql', 'my.cnf', '75', 'mysqld', 'text', 'innodb_max_dirty_pages_pct', '脏页百分比', 'NULL', '0', '^([0-9]|[0-9]\\.\\d+|[1-9]\\d|[1-9]\\d\\.\\d+)$', '请输入1到99.99之间的数字', '请输入1到99.99之间的数字', '2', '5223', 'NULL', 'NULL', '1', 'long', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5224', 'mysql', 'my.cnf', '1', 'mysqld', 'radio', 'lower_case_table_names', '是否区分大小写', '{\"0\":0,\"1\":1,\"2\":2}', '0', 'NULL', 'NULL', 'NULL', '1', '5224', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5225', 'mysql', 'my.cnf', 'ON', 'mysqld', 'radio', 'innodb_file_per_table', '是否使用独立表空间', '{\"使用\":\"ON\",\"不使用\":\"OFF\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5225', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5226', 'mysql', 'my.cnf', '-1', 'mysqld', 'text', 'innodb_open_files', '限制Innodb能打开的表数据', 'NULL', '0', '^([1-9]\\d{1,8}|[1-3]\\d{0,9}|4[0-1]\\d{0,8}|42[0-8]\\d{0,7}|429[0-3]\\d{0,6}|4294[0-8]\\d{0,5}|4294900000|-1)$', '请输入-1或者10到4294900000之间的整数', '请输入-1或者10到4294900000之间的整数', '2', '5226', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5227', 'mysql', 'my.cnf', '0', 'mysqld', 'text', 'innodb_thread_concurrency', '并发数', 'NULL', '0', '^(?:(?!0{1,3})\\d{1,3}|10{3}|0)$', '请输入0到1000之间的整数', '请输入0到1000之间的整数', '2', '5227', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5228', 'mysql', 'my.cnf', '1', 'mysqld', 'radio', 'innodb_flush_log_at_trx_commit', '磁盘写入策略', '{\"0\":0,\"1\":1,\"2\":2}', '0', 'NULL', 'NULL', 'NULL', '2', '5228', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5229', 'mysql', 'my.cnf', '400', 'mysqld', 'text', 'max_allowed_packet', '服务接受的数据包大小', 'NULL', '1', '^([1-9]|[1-9]\\d{0,2}|10[0-1]\\d|102[0-4])$', '请输入1到1024之间的整数', '请输入1到1024之间的整数', '2', '5229', 'M', 'M', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5230', 'mysql', 'my.cnf', '480', 'mysqld', 'text', 'interactive_timeout', 'MySQL连接的最大空闲时间(交互式连接)', 'NULL', '60', '^\\+?[1-9]\\d*$', '请输入大于1的整数', '请输入大于1的整数', '2', '5230', 'NULL', '分钟', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5231', 'mysql', 'my.cnf', '480', 'mysqld', 'text', 'wait_timeout', 'MySQL连接的最大空闲时间(非交互式连接)', 'NULL', '60', '^([1-9]\\d{0,4}|[1-4]\\d{5}|5[0-1]\\d{4}|52[0-4]\\d{3}|525[0-5]\\d{2}|525600)$', '请输入1到525600的整数', '请输入1到525600的整数', '2', '5231', 'NULL', '分钟', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5232', 'mysql', 'my.cnf', '8760', 'mysqld', 'text', 'lock_wait_timeout', '获取元数据锁的超时时间', 'NULL', '3600', '^([1-9]\\d{0,2}|[1-7]\\d{3}|8\\d{4}|8[0-6]\\d{2}|87[0-5]\\d{1}|8760)$', '请输入1到8760的整数', '请输入1到8760的整数', '2', '5232', 'NULL', '小时', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5233', 'mysql', 'my.cnf', 'utf8', 'mysqld', 'text', 'character-set-server', '服务器使用的字符集', 'NULL', '0', 'NULL', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5233', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5234', 'mysql', 'my.cnf', 'SYSTEM', 'mysqld', 'radio', 'log_timestamps', '日志显示时区', '{\"UTC\":\"UTC\",\"SYSTEM\":\"SYSTEM\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5234', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5235', 'mysql', 'my.cnf', '0', 'mysqld', 'text', 'max_user_connections', '每个账户的最大连接数', 'NULL', '0', '^([1-9]\\d{0,8}|[1-3]\\d{0,9}|4[0-1]\\d{0,8}|42[0-8]\\d{0,7}|429[0-3]\\d{0,6}|4294[0-8]\\d{0,5}|4294900000|0)$', '请输入0到4294900000之间的整数', '请输入0到4294900000之间的整数', '2', '5235', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5236', 'mysql', 'my.cnf', 'off', 'mysqld', 'radio', 'federated', '开启federated引擎', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5236', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5237', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'slow_query_log', '开启慢查询日志', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5237', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5238', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'log_queries_not_using_indexes', '将未引用索引的查询记入慢查询日志中', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5238', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5239', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'log_slow_admin_statements', '将慢管理语句等记入慢查询日志', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5239', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5240', 'mysql', 'my.cnf', '10', 'mysqld', 'text', 'long_query_time', '慢查询阈值，当查询时间多于设定的阈值时，记录日志', 'NULL', '0', '^(0|[1-9]\\d*)$', '请输入大于等于0的整数', '请输入大于等于0的整数', '2', '5240', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5241', 'mysql', 'my.cnf', '1', 'mysqld', 'radio', 'log_bin_trust_function_creators', '是否可以信任存储函数创建者', '{\"是\":\"1\",\"否\":\"0\"}', '0', 'NULL', 'NULL', '', '2', '5241', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5242', 'mysql', 'my.cnf', '', 'mysqld', 'text', 'sql_mode', '定义MySQL应该支持的sql语法，对数据的校验等', 'NULL', '0', 'NULL', '请输入ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION中的一个或多个', '请输入ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION中的一个或多个', '2', '5242', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5243', 'mysql', 'my.cnf', 'ON', 'mysqld', 'radio', 'innodb_large_prefix', '启用列索引超长长度限制', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', '', '2', '5243', 'NULL', 'NULL', '1', 'String', 'data-governance-v4.1');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5251', 'mysql', 'my.cnf', '16', 'mysqld', 'text', 'innodb_log_buffer_size', '缓冲日志数据的缓冲区的大小', 'NULL', '1', '^([1-9]|[1-9]\\d{1,2}|[1-3]\\d{3}|40[0-8]\\d|409[0-6])$', '请输入1到4096之间的整数', '请输入1到4096之间的整数', '2', '5251', 'M', 'M', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5252', 'mysql', 'my.cnf', '48', 'mysqld', 'text', 'innodb_log_file_size', '日志组中每个日志文件的大小', 'NULL', '1', '^([4-9]|[1-9]\\d+)$', '请输入4到262144之间的整数', '请输入4到262144之间的整数', '2', '5252', 'M', 'M', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5253', 'mysql', 'my.cnf', '2', 'mysqld', 'text', 'innodb_log_files_in_group', '日志组文件个数', 'NULL', '0', '^[2-9]$|^[1-9]\\d$|^100$', '请输入2到100之间的整数', '请输入2到100之间的整数', '1', '5253', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5254', 'mysql', 'my.cnf', '50', 'mysqld', 'text', 'innodb_lock_wait_timeout', 'innodb行锁锁定等待超时', 'NULL', '1', '^([1-9]\\d{0,8}|10[0-6]\\d{0,7}|107[0-2]\\d{0,6}|1073[0-6]\\d{0,5}|1073700000)$', '请输入1到1073700000之间的整数', '请输入1到1073700000之间的整数', '2', '5254', 'NULL', '秒', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5255', 'mysql', 'my.cnf', '100', 'mysqld', 'text', 'max_connect_errors', '每个客户端连接最大的错误允许数量', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5255', 'NULL', 'B', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5256', 'mysql', 'my.cnf', 'InnoDB', 'mysqld', 'radio', 'default_tmp_storage_engine', '临时表的默认存储引擎', '{\"InnoDB\":\"InnoDB\",\"MyISAM\":\"MyISAM\",\"MRG_MYISAM\":\"MRG_MYISAM\",\"MEMORY\":\"MEMORY\",\"BLACKHOLE\":\"BLACKHOLE\",\"CSV\":\"CSV\",\"ARCHIVE\":\"ARCHIVE\",\"PERFORMANCE_SCHEMA\":\"PERFORMANCE_SCHEMA\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5256', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5257', 'mysql', 'my.cnf', 'InnoDB', 'mysqld', 'radio', 'default_storage_engine', '永久表的默认存储引擎', '{\"InnoDB\":\"InnoDB\",\"MyISAM\":\"MyISAM\",\"MRG_MYISAM\":\"MRG_MYISAM\",\"MEMORY\":\"MEMORY\",\"BLACKHOLE\":\"BLACKHOLE\",\"CSV\":\"CSV\",\"ARCHIVE\":\"ARCHIVE\",\"PERFORMANCE_SCHEMA\":\"PERFORMANCE_SCHEMA\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5257', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5258', 'mysql', 'my.cnf', 'binary', 'mysqld', 'text', 'character_set_filesystem', '数据库文件系统字符集', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5258', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5259', 'mysql', 'my.cnf', 'MIXED', 'mysqld', 'radio', 'binlog_format', 'MySQL的复制方式', '{\"ROW\":\"ROW\",\"STATEMENT\":\"STATEMENT\",\"MIXED\":\"MIXED\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5259', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5260', 'mysql', 'my.cnf', 'utf8mb4_general_ci', 'mysqld', 'text', 'collation-server', '服务器默认排序规则', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5260', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5261', 'mysql', 'my.cnf', 'utf8mb4', 'client', 'text', 'default-character-set', 'MySQL数据库默认字符集', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5261', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5262', 'mysql', 'my.cnf', '-1', 'mysqld', 'text', 'thread_cache_size', '线程缓存区大小', 'NULL', '1', '^(-1|0|[1-9]\\d{0,3}|1[0-5]\\d{1,3}|16[0-2]\\d{0,2}|163[0-7]\\d|1638[0-4])$', '请输入-1到16384的整数', '请输入-1到16384的整数', '1', '5262', 'NULL', 'B', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5263', 'mysql', 'my.cnf', '16', 'mysqld', 'text', 'tmp_table_size', '临时表使用缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5263', 'M', 'M', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5264', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'sort_buffer_size', '排序使用的缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5264', 'M', 'M', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5265', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'read_buffer_size', '读入缓冲区', 'NULL', '1', '^([1-9]|[1-9]\\d{1,2}|1\\d{3}|20[0-3]\\d|204[0-7])$', '请输入1到2047之间的整数', '请输入1到2047之间的整数', '2', '5265', 'M', 'M', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5266', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'join_buffer_size', '表关联使用的缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5266', 'M', 'M', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5267', 'mysql', 'my.cnf', '1024', 'mysqld', 'text', 'max_connections', '最大连接数', 'NULL', '0', '^(?:(?!0{1,5})\\d{1,5}|10{5})$', '请输入1到100000之间的整数', '请输入1到100000之间的整数', '1', '5267', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5268', 'mysql', 'my.cnf', '2', 'mysqld', 'text', 'table_open_cache', '所有线程打开表的数量', 'NULL', '1', '^([1-9][\\d]{0,1}|[1-4]\\d{2}|50\\d|51[0-2])$', '请输入1到512之间的整数', '请输入1到512之间的整数', '2', '5268', 'K', 'K', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5269', 'mysql', 'my.cnf', '128', 'mysqld', 'text', 'innodb_buffer_pool_size', '缓冲池字节大小', 'NULL', '1', '^([5-9]|[1-9]\\d{1,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入5到17592000000000之间的整数', '请输入5到17592000000000之间的整数', '1', '5269', 'M', 'M', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5270', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'innodb_buffer_pool_instances', 'InnoDB缓冲池划分的区域数量', 'NULL', '0', '^([1-9]|[1-5][0-9]|6[0-4])$', '请输入1到64之间的整数', '请输入1到64之间的整数', '2', '5270', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5271', 'mysql', 'my.cnf', 'READ-COMMITTED', 'mysqld', 'radio', 'transaction-isolation', '事物隔离级别', '{\"READ-UNCOMMITTED\":\"READ-UNCOMMITTED\",\"READ-COMMITTED\":\"READ-COMMITTED\",\"REPEATABLE-READ\":\"REPEATABLE-READ\",\"SERIALIZABLE\":\"SERIALIZABLE\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5271', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5272', 'mysql', 'my.cnf', '75', 'mysqld', 'text', 'innodb_max_dirty_pages_pct', '脏页百分比', 'NULL', '0', '^([0-9]|[0-9]\\.\\d+|[1-9]\\d|[1-9]\\d\\.\\d+)$', '请输入1到99.99之间的数字', '请输入1到99.99之间的数字', '2', '5272', 'NULL', 'NULL', '1', 'long', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5273', 'mysql', 'my.cnf', '1', 'mysqld', 'radio', 'lower_case_table_names', '是否区分大小写', '{\"0\":0,\"1\":1,\"2\":2}', '0', 'NULL', 'NULL', 'NULL', '1', '5273', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5274', 'mysql', 'my.cnf', 'ON', 'mysqld', 'radio', 'innodb_file_per_table', '是否使用独立表空间', '{\"使用\":\"ON\",\"不使用\":\"OFF\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5274', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5275', 'mysql', 'my.cnf', '-1', 'mysqld', 'text', 'innodb_open_files', '限制Innodb能打开的表数据', 'NULL', '0', '^([1-9]\\d{1,8}|[1-3]\\d{0,9}|4[0-1]\\d{0,8}|42[0-8]\\d{0,7}|429[0-3]\\d{0,6}|4294[0-8]\\d{0,5}|4294900000|-1)$', '请输入-1或者10到4294900000之间的整数', '请输入-1或者10到4294900000之间的整数', '2', '5275', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5276', 'mysql', 'my.cnf', '0', 'mysqld', 'text', 'innodb_thread_concurrency', '并发数', 'NULL', '0', '^(?:(?!0{1,3})\\d{1,3}|10{3}|0)$', '请输入0到1000之间的整数', '请输入0到1000之间的整数', '2', '5276', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5277', 'mysql', 'my.cnf', '1', 'mysqld', 'radio', 'innodb_flush_log_at_trx_commit', '磁盘写入策略', '{\"0\":0,\"1\":1,\"2\":2}', '0', 'NULL', 'NULL', 'NULL', '2', '5277', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5278', 'mysql', 'my.cnf', '400', 'mysqld', 'text', 'max_allowed_packet', '服务接受的数据包大小', 'NULL', '1', '^([1-9]|[1-9]\\d{0,2}|10[0-1]\\d|102[0-4])$', '请输入1到1024之间的整数', '请输入1到1024之间的整数', '2', '5278', 'M', 'M', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5279', 'mysql', 'my.cnf', '480', 'mysqld', 'text', 'interactive_timeout', 'MySQL连接的最大空闲时间(交互式连接)', 'NULL', '60', '^\\+?[1-9]\\d*$', '请输入大于1的整数', '请输入大于1的整数', '2', '5279', 'NULL', '分钟', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5280', 'mysql', 'my.cnf', '480', 'mysqld', 'text', 'wait_timeout', 'MySQL连接的最大空闲时间(非交互式连接)', 'NULL', '60', '^([1-9]\\d{0,4}|[1-4]\\d{5}|5[0-1]\\d{4}|52[0-4]\\d{3}|525[0-5]\\d{2}|525600)$', '请输入1到525600的整数', '请输入1到525600的整数', '2', '5280', 'NULL', '分钟', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5281', 'mysql', 'my.cnf', '8760', 'mysqld', 'text', 'lock_wait_timeout', '获取元数据锁的超时时间', 'NULL', '3600', '^([1-9]\\d{0,2}|[1-7]\\d{3}|8\\d{4}|8[0-6]\\d{2}|87[0-5]\\d{1}|8760)$', '请输入1到8760的整数', '请输入1到8760的整数', '2', '5281', 'NULL', '小时', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5282', 'mysql', 'my.cnf', 'utf8mb4', 'mysqld', 'text', 'character-set-server', '服务器使用的字符集', 'NULL', '0', 'NULL', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5282', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5283', 'mysql', 'my.cnf', 'SYSTEM', 'mysqld', 'radio', 'log_timestamps', '日志显示时区', '{\"UTC\":\"UTC\",\"SYSTEM\":\"SYSTEM\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5283', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5284', 'mysql', 'my.cnf', '0', 'mysqld', 'text', 'max_user_connections', '每个账户的最大连接数', 'NULL', '0', '^([1-9]\\d{0,8}|[1-3]\\d{0,9}|4[0-1]\\d{0,8}|42[0-8]\\d{0,7}|429[0-3]\\d{0,6}|4294[0-8]\\d{0,5}|4294900000|0)$', '请输入0到4294900000之间的整数', '请输入0到4294900000之间的整数', '2', '5284', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5285', 'mysql', 'my.cnf', 'off', 'mysqld', 'radio', 'federated', '开启federated引擎', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5285', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5286', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'slow_query_log', '开启慢查询日志', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5286', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5287', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'log_queries_not_using_indexes', '将未引用索引的查询记入慢查询日志中', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5287', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5288', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'log_slow_admin_statements', '将慢管理语句等记入慢查询日志', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5288', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5289', 'mysql', 'my.cnf', '10', 'mysqld', 'text', 'long_query_time', '慢查询阈值，当查询时间多于设定的阈值时，记录日志', 'NULL', '0', '^(0|[1-9]\\d*)$', '请输入大于等于0的整数', '请输入大于等于0的整数', '2', '5289', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5290', 'mysql', 'my.cnf', '0', 'mysqld', 'radio', 'log_bin_trust_function_creators', '是否可以信任存储函数创建者', '{\"是\":\"1\",\"否\":\"0\"}', '0', 'NULL', 'NULL', '', '2', '5290', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5291', 'mysql', 'my.cnf', '', 'mysqld', 'text', 'sql_mode', '定义MySQL应该支持的sql语法，对数据的校验等', 'NULL', '0', 'NULL', '请输入ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION中的一个或多个', '请输入ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION中的一个或多个', '2', '5291', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5292', 'mysql', 'my.cnf', 'ON', 'mysqld', 'radio', 'innodb_large_prefix', '启用列索引超长长度限制', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', '', '2', '5292', 'NULL', 'NULL', '1', 'String', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5300', 'mysql', 'my.cnf', '32', 'mysqld', 'text', 'binlog_cache_size', '开启log-bin时，为每个客户端分配的二进制日志缓存大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '1', '5300', 'K', 'K', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5301', 'mysql', 'my.cnf', '16', 'mysqld', 'text', 'innodb_log_buffer_size', '缓冲日志数据的缓冲区的大小', 'NULL', '1', '^([1-9]|[1-9]\\d{1,2}|[1-3]\\d{3}|40[0-8]\\d|409[0-6])$', '请输入1到4096之间的整数', '请输入1到4096之间的整数', '2', '5301', 'M', 'M', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5302', 'mysql', 'my.cnf', '48', 'mysqld', 'text', 'innodb_log_file_size', '日志组中每个日志文件的大小', 'NULL', '1', '^([4-9]|[1-9]\\d+)$', '请输入4到262144之间的整数', '请输入4到262144之间的整数', '2', '5302', 'M', 'M', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5303', 'mysql', 'my.cnf', '2', 'mysqld', 'text', 'innodb_log_files_in_group', '日志组文件个数', 'NULL', '0', '^[2-9]$|^[1-9]\\d$|^100$', '请输入2到100之间的整数', '请输入2到100之间的整数', '1', '5303', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5304', 'mysql', 'my.cnf', '50', 'mysqld', 'text', 'innodb_lock_wait_timeout', 'innodb行锁锁定等待超时', 'NULL', '1', '^([1-9]\\d{0,8}|10[0-6]\\d{0,7}|107[0-2]\\d{0,6}|1073[0-6]\\d{0,5}|1073700000)$', '请输入1到1073700000之间的整数', '请输入1到1073700000之间的整数', '2', '5304', 'NULL', '秒', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5305', 'mysql', 'my.cnf', '100', 'mysqld', 'text', 'max_connect_errors', '每个客户端连接最大的错误允许数量', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5305', 'NULL', 'B', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5306', 'mysql', 'my.cnf', 'InnoDB', 'mysqld', 'radio', 'default_tmp_storage_engine', '临时表的默认存储引擎', '{\"InnoDB\":\"InnoDB\",\"MyISAM\":\"MyISAM\",\"MRG_MYISAM\":\"MRG_MYISAM\",\"MEMORY\":\"MEMORY\",\"BLACKHOLE\":\"BLACKHOLE\",\"CSV\":\"CSV\",\"ARCHIVE\":\"ARCHIVE\",\"PERFORMANCE_SCHEMA\":\"PERFORMANCE_SCHEMA\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5306', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5307', 'mysql', 'my.cnf', 'InnoDB', 'mysqld', 'radio', 'default_storage_engine', '永久表的默认存储引擎', '{\"InnoDB\":\"InnoDB\",\"MyISAM\":\"MyISAM\",\"MRG_MYISAM\":\"MRG_MYISAM\",\"MEMORY\":\"MEMORY\",\"BLACKHOLE\":\"BLACKHOLE\",\"CSV\":\"CSV\",\"ARCHIVE\":\"ARCHIVE\",\"PERFORMANCE_SCHEMA\":\"PERFORMANCE_SCHEMA\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5307', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5308', 'mysql', 'my.cnf', 'binary', 'mysqld', 'text', 'character_set_filesystem', '数据库文件系统字符集', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5308', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5309', 'mysql', 'my.cnf', 'MIXED', 'mysqld', 'radio', 'binlog_format', 'MySQL的复制方式', '{\"ROW\":\"ROW\",\"STATEMENT\":\"STATEMENT\",\"MIXED\":\"MIXED\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5309', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5310', 'mysql', 'my.cnf', 'utf8_general_ci', 'mysqld', 'text', 'collation-server', '服务器默认排序规则', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5310', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5311', 'mysql', 'my.cnf', 'utf8', 'client', 'text', 'default-character-set', 'MySQL数据库默认字符集', 'NULL', '0', '[^\\0]+', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5311', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5312', 'mysql', 'my.cnf', '-1', 'mysqld', 'text', 'thread_cache_size', '线程缓存区大小', 'NULL', '1', '^(-1|0|[1-9]\\d{0,3}|1[0-5]\\d{1,3}|16[0-2]\\d{0,2}|163[0-7]\\d|1638[0-4])$', '请输入-1到16384的整数', '请输入-1到16384的整数', '1', '5312', 'NULL', 'B', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5313', 'mysql', 'my.cnf', '16', 'mysqld', 'text', 'tmp_table_size', '临时表使用缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5313', 'M', 'M', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5314', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'sort_buffer_size', '排序使用的缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5314', 'M', 'M', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5315', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'read_buffer_size', '读入缓冲区', 'NULL', '1', '^([1-9]|[1-9]\\d{1,2}|1\\d{3}|20[0-3]\\d|204[0-7])$', '请输入1到2047之间的整数', '请输入1到2047之间的整数', '2', '5315', 'M', 'M', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5316', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'join_buffer_size', '表关联使用的缓冲区大小', 'NULL', '1', '^([1-9]\\d{0,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入1到17592000000000之间的整数', '请输入1到17592000000000之间的整数', '2', '5316', 'M', 'M', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5317', 'mysql', 'my.cnf', '1024', 'mysqld', 'text', 'max_connections', '最大连接数', 'NULL', '0', '^(?:(?!0{1,5})\\d{1,5}|10{5})$', '请输入1到100000之间的整数', '请输入1到100000之间的整数', '1', '5317', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5318', 'mysql', 'my.cnf', '2', 'mysqld', 'text', 'table_open_cache', '所有线程打开表的数量', 'NULL', '1', '^([1-9][\\d]{0,1}|[1-4]\\d{2}|50\\d|51[0-2])$', '请输入1到512之间的整数', '请输入1到512之间的整数', '2', '5318', 'K', 'K', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5319', 'mysql', 'my.cnf', '128', 'mysqld', 'text', 'innodb_buffer_pool_size', '缓冲池字节大小', 'NULL', '1', '^([5-9]|[1-9]\\d{1,12}|1[0-6]\\d{0,12}|17[0-4]\\d{0,11}|175[0-8]\\d{0,10}|1759[0-1]\\d{0,9}|17592000000000)$', '请输入5到17592000000000之间的整数', '请输入5到17592000000000之间的整数', '1', '5319', 'M', 'M', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5320', 'mysql', 'my.cnf', '1', 'mysqld', 'text', 'innodb_buffer_pool_instances', 'InnoDB缓冲池划分的区域数量', 'NULL', '0', '^([1-9]|[1-5][0-9]|6[0-4])$', '请输入1到64之间的整数', '请输入1到64之间的整数', '2', '5320', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5321', 'mysql', 'my.cnf', 'READ-COMMITTED', 'mysqld', 'radio', 'transaction-isolation', '事物隔离级别', '{\"READ-UNCOMMITTED\":\"READ-UNCOMMITTED\",\"READ-COMMITTED\":\"READ-COMMITTED\",\"REPEATABLE-READ\":\"REPEATABLE-READ\",\"SERIALIZABLE\":\"SERIALIZABLE\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5321', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5322', 'mysql', 'my.cnf', '75', 'mysqld', 'text', 'innodb_max_dirty_pages_pct', '脏页百分比', 'NULL', '0', '^([0-9]|[0-9]\\.\\d+|[1-9]\\d|[1-9]\\d\\.\\d+)$', '请输入1到99.99之间的数字', '请输入1到99.99之间的数字', '2', '5322', 'NULL', 'NULL', '1', 'long', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5323', 'mysql', 'my.cnf', '1', 'mysqld', 'radio', 'lower_case_table_names', '是否区分大小写', '{\"0\":0,\"1\":1,\"2\":2}', '0', 'NULL', 'NULL', 'NULL', '1', '5323', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5324', 'mysql', 'my.cnf', 'ON', 'mysqld', 'radio', 'innodb_file_per_table', '是否使用独立表空间', '{\"使用\":\"ON\",\"不使用\":\"OFF\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5324', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5325', 'mysql', 'my.cnf', '-1', 'mysqld', 'text', 'innodb_open_files', '限制Innodb能打开的表数据', 'NULL', '0', '^([1-9]\\d{1,8}|[1-3]\\d{0,9}|4[0-1]\\d{0,8}|42[0-8]\\d{0,7}|429[0-3]\\d{0,6}|4294[0-8]\\d{0,5}|4294900000|-1)$', '请输入-1或者10到4294900000之间的整数', '请输入-1或者10到4294900000之间的整数', '2', '5325', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5326', 'mysql', 'my.cnf', '0', 'mysqld', 'text', 'innodb_thread_concurrency', '并发数', 'NULL', '0', '^(?:(?!0{1,3})\\d{1,3}|10{3}|0)$', '请输入0到1000之间的整数', '请输入0到1000之间的整数', '2', '5326', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5327', 'mysql', 'my.cnf', '1', 'mysqld', 'radio', 'innodb_flush_log_at_trx_commit', '磁盘写入策略', '{\"0\":0,\"1\":1,\"2\":2}', '0', 'NULL', 'NULL', 'NULL', '2', '5327', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5328', 'mysql', 'my.cnf', '400', 'mysqld', 'text', 'max_allowed_packet', '服务接受的数据包大小', 'NULL', '1', '^([1-9]|[1-9]\\d{0,2}|10[0-1]\\d|102[0-4])$', '请输入1到1024之间的整数', '请输入1到1024之间的整数', '2', '5328', 'M', 'M', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5329', 'mysql', 'my.cnf', '480', 'mysqld', 'text', 'interactive_timeout', 'MySQL连接的最大空闲时间(交互式连接)', 'NULL', '60', '^\\+?[1-9]\\d*$', '请输入大于1的整数', '请输入大于1的整数', '2', '5329', 'NULL', '分钟', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5330', 'mysql', 'my.cnf', '480', 'mysqld', 'text', 'wait_timeout', 'MySQL连接的最大空闲时间(非交互式连接)', 'NULL', '60', '^([1-9]\\d{0,4}|[1-4]\\d{5}|5[0-1]\\d{4}|52[0-4]\\d{3}|525[0-5]\\d{2}|525600)$', '请输入1到525600的整数', '请输入1到525600的整数', '2', '5330', 'NULL', '分钟', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5331', 'mysql', 'my.cnf', '8760', 'mysqld', 'text', 'lock_wait_timeout', '获取元数据锁的超时时间', 'NULL', '3600', '^([1-9]\\d{0,2}|[1-7]\\d{3}|8\\d{4}|8[0-6]\\d{2}|87[0-5]\\d{1}|8760)$', '请输入1到8760的整数', '请输入1到8760的整数', '2', '5331', 'NULL', '小时', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5332', 'mysql', 'my.cnf', 'utf8', 'mysqld', 'text', 'character-set-server', '服务器使用的字符集', 'NULL', '0', 'NULL', '可在MySQL官网查看支持哪些字符集', '可在MySQL官网查看支持哪些字符集', '0', '5332', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5333', 'mysql', 'my.cnf', 'SYSTEM', 'mysqld', 'radio', 'log_timestamps', '日志显示时区', '{\"UTC\":\"UTC\",\"SYSTEM\":\"SYSTEM\"}', '0', 'NULL', 'NULL', 'NULL', '1', '5333', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5334', 'mysql', 'my.cnf', '0', 'mysqld', 'text', 'max_user_connections', '每个账户的最大连接数', 'NULL', '0', '^([1-9]\\d{0,8}|[1-3]\\d{0,9}|4[0-1]\\d{0,8}|42[0-8]\\d{0,7}|429[0-3]\\d{0,6}|4294[0-8]\\d{0,5}|4294900000|0)$', '请输入0到4294900000之间的整数', '请输入0到4294900000之间的整数', '2', '5334', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5335', 'mysql', 'my.cnf', 'off', 'mysqld', 'radio', 'federated', '开启federated引擎', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5335', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5336', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'slow_query_log', '开启慢查询日志', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5336', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5337', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'log_queries_not_using_indexes', '将未引用索引的查询记入慢查询日志中', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5337', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5338', 'mysql', 'my.cnf', 'on', 'mysqld', 'radio', 'log_slow_admin_statements', '将慢管理语句等记入慢查询日志', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', 'NULL', '2', '5338', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5339', 'mysql', 'my.cnf', '10', 'mysqld', 'text', 'long_query_time', '慢查询阈值，当查询时间多于设定的阈值时，记录日志', 'NULL', '0', '^(0|[1-9]\\d*)$', '请输入大于等于0的整数', '请输入大于等于0的整数', '2', '5339', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5340', 'mysql', 'my.cnf', '0', 'mysqld', 'radio', 'log_bin_trust_function_creators', '是否可以信任存储函数创建者', '{\"是\":\"1\",\"否\":\"0\"}', '0', 'NULL', 'NULL', '', '2', '5340', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5341', 'mysql', 'my.cnf', '', 'mysqld', 'text', 'sql_mode', '定义MySQL应该支持的sql语法，对数据的校验等', 'NULL', '0', 'NULL', '请输入ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION中的一个或多个', '请输入ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION中的一个或多个', '2', '5341', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5342', 'mysql', 'my.cnf', 'ON', 'mysqld', 'radio', 'innodb_large_prefix', '启用列索引超长长度限制', '{\"开启\":\"on\",\"不开启\":\"off\"}', '0', 'NULL', 'NULL', '', '2', '5342', 'NULL', 'NULL', '1', 'String', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5343', 'mysql', 'my.cnf', '7', 'mysqld', 'text', 'expire_logs_days', 'binlog日志文件保留时间', 'NULL', '1', '^(0|[1-9]\\d*)$', '请输入0或大于0的整数', '请输入0或大于0的整数', '2', '5343', 'NULL', 'NULL', '1', 'int', 'data-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5344', 'mysql', 'my.cnf', '7', 'mysqld', 'text', 'expire_logs_days', 'binlog日志文件保留时间', 'NULL', '1', '^(0|[1-9]\\d*)$', '请输入0或大于0的整数', '请输入0或大于0的整数', '2', '5344', 'NULL', 'NULL', '1', 'int', 'data-governance-cloud-v1.0');
INSERT INTO `bdos_stateful_service_component_default_config` (`id`,`app_type`,`cnf_file`,`def_value`,`group`,`input_type`,`key`,`name`,`optional`,`product`,`regx`,`regx_remark`,`remark`,`show_level`,`sort`,`unit`,`unit_remark`,`update_enable`,`value_type`,`version`) VALUES ('5345', 'mysql', 'my.cnf', '7', 'mysqld', 'text', 'expire_logs_days', 'binlog日志文件保留时间', 'NULL', '1', '^(0|[1-9]\\d*)$', '请输入0或大于0的整数', '请输入0或大于0的整数', '2', '5345', 'NULL', 'NULL', '1', 'int', 'data-governance-v4.1');

-- ----------------------------
-- 修改：bdos_service表，新增字段host_aliases、init_container
-- ----------------------------
alter table `bdos_service` add `host_aliases` VARCHAR(255) default null;
alter table `bdos_service` add `init_container` VARCHAR(255) default null;

-- ----------------------------
-- 修改：bdos_service_and_ceph_file表，新增字段service_type
-- ----------------------------
alter table `bdos_service_and_ceph_file` add `service_type` VARCHAR(64) default null;
update `bdos_service_and_ceph_file` set `service_type`='service';

-- ----------------------------
-- 修改：bdos_springcloud_service表，删除字段storage
-- ----------------------------
alter table `bdos_springcloud_service` drop column `storage`;





-- ----------------------------
-- 修改：bdos_springcloud_application表，删除字段storage
-- ----------------------------
alter table `bdos_springcloud_application` drop column `storage`;

-- ----------------------------
-- 修改：bdos_stateful_service_unit_version表中rabbitmq的镜像名称
-- ----------------------------
update `bdos_stateful_service_unit_version` set `version_path`='{{harbor.dns}}:{{harbor.port}}/library/rabbitmq:3.7.17-management' where id=42;


-- ----------------------------
-- 修改：bdos_ingress_proxy表中nginx_config字段的类型
-- ----------------------------
alter table bdos_ingress_proxy modify column nginx_config text;