- name: 安装ceph，rgw
  vars:
    packages:
    - ceph-deploy
    - ceph
    - ceph-radosgw
  yum: name={{packages}} state=installed update_cache=yes


- name: 停止已有的rgw服务
  shell: |
    systemctl stop ceph-radosgw@rgw.{{rgw_hostname}}.service
    systemctl disable ceph-radosgw@rgw.{{rgw_hostname}}.service
  ignore_errors: yes

- name: 从控制机同步配置文件
  copy: src={{ceph_controller_conf_dir}}/{{item}} dest={{ceph_conf_dir}}/{{item}} mode=0644
  with_items: "{{ceph_conf_list}}"

- name: 创建工作目录
  file: path={{ceph_work_dir}}/radosgw/ceph-rgw.{{rgw_hostname}} state=directory

- name: 创建密钥
  shell: ceph auth get-or-create client.rgw.{{rgw_hostname}} mon 'allow rwx' osd 'allow rwx' -o /var/lib/ceph/radosgw/ceph-rgw.{{rgw_hostname}}/keyring

#- name: 修改配置文件
#  blockinfile:
#    path="{{ceph_conf_dir}}/ceph.conf"
#    marker="# rgw-{{rgw_hostname}}"
#    block="[client.radosgw.{{rgw_hostname}}]\nrgw_frontends = civetweb port={{civetweb_port}}\nrbd_default_format=2\nrbd_default_features = 1\nmon clock drift allowed = 2\nmon clock drift warn backoff = 30\nmon data avail warn = 5\nmon data avail crit = 0.2\n"

- name: 启动rgw
  shell: |
    systemctl enable ceph-radosgw@rgw.{{rgw_hostname}}.service
    systemctl start ceph-radosgw@rgw.{{rgw_hostname}}.service
    systemctl enable ceph.target

- name: 创建rgw的相关资源
  shell: |
    if [[ $(radosgw-admin metadata get user:admin 2>/dev/null) == '' ]]; then
      radosgw-admin user create --uid="admin" --display-name="admin" 2>/dev/null
      radosgw-admin subuser create --uid="admin" --subuser="admin:swift" --access=full 2>/dev/null
      radosgw-admin key create --subuser=admin:swift --key-type=swift --gen-secret 2>/dev/null
      radosgw-admin quota set --quota-scope=user --uid=admin --max-objects=1024 --max-size=1024B 2>/dev/null
      radosgw-admin quota enable --quota-scope=user --uid=admin 2>/dev/null
      radosgw-admin quota set --uid=admin --quota-scope=bucket --max-objects=1024 --max-size=1024B 2>/dev/null
      radosgw-admin quota enable --quota-scope=bucket --uid=admin 2>/dev/null
      radosgw-admin caps add --uid=admin --caps="buckets=*; metadata=*; usage=*; users=*;" 2>/dev/null
    fi
    exit 0
