- name: 获取本机所有服务
  service_facts:

- name: 停止已有的mon服务
  vars:
    service_name: "ceph-mon@{{mon_hostname}}.service"
  service: name=ceph-mon@{{mon_hostname}} state=stopped enabled=no
  when: service_name in ansible_facts.services

- name: 删除已有的mon数据
  shell: |
    rm -rf {{ceph_work_dir}}/mon/*

- name: 安装ceph
  vars:
    packages:
    - ceph-deploy
    - ceph
  yum: name={{packages}} state=installed update_cache=yes

- name: 从控制机同步配置文件和密钥环
  copy: src={{ceph_controller_conf_dir}}/{{item}} dest={{ceph_conf_dir}}/{{item}} mode=0644
  with_items: "{{ceph_conf_list}}"

- name: 创建集群所需文件（monmap）
  args:
    chdir: "{{ceph_conf_dir}}/"
  shell:  |
    rm -rf monmap
    fsid=`echo $(cat ceph.conf | grep -E '^'mon_initial_members'\ *=' | cut -d= -f2)`
    monmaptool --create --fsid $fsid monmap

- name: 获取mon_initial_members
  shell: echo $(cat {{ceph_conf_dir}}/ceph.conf | grep -E '^'mon_initial_members'\ *=' | cut -d= -f2)
  register: mon_initial_members

- name: 获取mon_host
  shell: echo $(cat {{ceph_conf_dir}}/ceph.conf | grep -E '^'mon_host'\ *=' | cut -d= -f2)
  register: mon_host

- name: 给monmap添加主机映射
  shell: |
    monmaptool --add {{item[0]}} {{item[1]}} {{ceph_conf_dir}}/monmap
  with_together:
  - "{{mon_initial_members.stdout.split(',')}}"
  - "{{mon_host.stdout.split(',')}}"

- name: 修改mon所需文件的用户
  file: path={{ceph_conf_dir}}/ owner=ceph group=ceph
  with_items:
  - "monmap"
  - "ceph.mon.keyring"

- name: 创建mon工作目录
  file: path={{ceph_work_dir}}/mon/ceph-{{mon_hostname}} state=directory owner=ceph group=ceph

- name: 初始化mon db
  shell: sudo -u ceph ceph-mon --mkfs -i {{mon_hostname}} --monmap {{ceph_conf_dir}}/monmap --keyring {{ceph_conf_dir}}/ceph.mon.keyring

- name: 启动mon
  shell: |
    systemctl enable ceph-mon@{{mon_hostname}}
    systemctl start ceph-mon@{{mon_hostname}}
    systemctl enable ceph.target
