- name: 安装ceph
  vars:
    packages:
    - ceph-deploy
    - ceph
  yum: name={{packages}} state=installed update_cache=yes

- name: 清理已有的mds
  shell: |
    systemctl stop ceph-mds@{{mds_hostname}}
    systemctl disable ceph-mds@{{mds_hostname}}
    rm -rf {{ceph_work_dir}}/mds/ceph-{{mds_hostname}}
  ignore_errors: yes

- name: 从控制机同步配置文件
  copy: src={{ceph_controller_conf_dir}}/{{item}} dest={{ceph_conf_dir}}/{{item}} mode=0644
  with_items: "{{ceph_conf_list}}"

- name: 创建工作目录
  file: path={{ceph_work_dir}}/mds/ceph-{{mds_hostname}} state=directory owner=ceph group=ceph

- name: 创建密钥
  shell: |
    ceph auth get-or-create mds.$(hostname) mon 'allow profile mds' osd 'allow *' mds 'allow' -o /var/lib/ceph/mds/ceph-$(hostname)/keyring
    chown ceph:ceph -R {{ceph_work_dir}}/mds/ceph-{{mds_hostname}}

- name: 修改配置文件，使mds成为备节点
  lineinfile:
    path: "/usr/lib/systemd/system/ceph-mds@.service"
    regexp: "^ExecStart"
    line: "ExecStart=/usr/bin/ceph-mds --hot-standby 0 -f --cluster ${CLUSTER} --id %i --setuser ceph --setgroup ceph"
  when: backup_flag

- name: 启动mds
  shell: |
    systemctl enable ceph-mds@{{mds_hostname}}
    systemctl start ceph-mds@{{mds_hostname}}
    systemctl enable ceph.target

- name: 创建ceph fs
  shell: |
    if [[ $(ceph fs ls | grep 'No filesystems') != '' ]]; then
      ceph osd pool create cephfs_data 64 64
      ceph osd pool create cephfs_metadata 64 64
      ceph fs new bonc_fs cephfs_metadata cephfs_data
    fi
  when: not backup_flag
