# part_info: {id: "",devName: "",devSizeUsed: 0,status: "2",name: "",partType: ""}

- name: 安装ceph-osd
  vars:
    packages:
    - ceph-deploy
    - ceph
    - xfs*
  yum: name={{packages}} state=installed update_cache=yes

- name: 从控制机同步配置文件
  copy: src={{ceph_controller_conf_dir}}/{{item}} dest={{ceph_conf_dir}}/{{item}} mode=0644
  with_items: "{{ceph_conf_list}}"

- name: 获取引导密钥环
  shell: |
    ceph auth get client.bootstrap-osd -o {{ceph_work_dir}}/bootstrap-osd/ceph.keyring
    chown ceph:ceph {{ceph_work_dir}}/bootstrap-osd/ceph.keyring 

- name: 安装osd
  include: add_osd.yml
  with_together:
  - "{{osd_data_list}}"
  - "{{osd_journal_list}}"
  loop_control:
      loop_var: item_osd
