- name: 安装ceph
  yum: name=ceph state=installed update_cache=yes

- name: 从控制机同步配置文件
  copy: src={{ceph_controller_conf_dir}}/{{item}} dest={{ceph_conf_dir}}/{{item}} mode=0644
  with_items: "{{ceph_conf_list}}"

#- name: 创建管理员密钥
#  file: path={{ceph_conf_dir}}/admin.secret state=touch mode=0644

#- name: 给密钥赋值
#  shell: cat {{ceph_conf_dir}}/ceph.client.admin.keyring | grep key | awk '{print $3}'  > {{ceph_conf_dir}}/admin.secret

#- name: 创建挂载目录
#  file: path={{mnt_dir}} state=directory

#- name: 获取mon ip列表
#  shell: ceph-osd --cluster=ceph --show-config-value=mon_host | awk -F ',' '{for(i=1;i<=NF;i++)print $i}'
#  register: mon_ip_list

#- name: 在控制机上挂载ceph文件系统
#  shell: mount -t ceph {{mon_ip_list.stdout_lines|join(':6789,')}}:6789:/ {{mnt_dir}} -o name=admin,secretfile={{ceph_conf_dir}}/admin.secret
