- name: 获取hostname
  shell: hostname
  register: hostname

- name: 查询 rgw 服务状态
  shell: systemctl status ceph-radosgw@rgw.{{hostname.stdout}} -l
  ignore_errors: yes
  register: service_result

- name: 打印 rgw 服务状态
  debug: msg={{service_result.stdout}}
