harbor:
  ip: "{{boots_global.COMPOSE_HARBOR_IP}}"
  dns: "{{(boots_global.COMPOSE_HARBOR_DNS=='')|ternary(boots_global.COMPOSE_HARBOR_IP,boots_global.COMPOSE_HARBOR_DNS)}}"
  port: "{{boots_global.PORT_HARBOR_HTTPS}}"