#  storage_driver: devicemapper,overlay2

- name: 将配置写入docker配置文件
  vars:
    docker_daemon:
      hosts:
      - "unix:///var/run/docker.sock"
      - "tcp://0.0.0.0:28015"
      data-root: "{{mount_path}}"
      log-driver: "json-file"
      exec-opts:
      - "native.cgroupdriver=systemd"
      runtimes:
        nvidia:
          path: "nvidia-container-runtime"
          runtimeArgs: []
      default-runtime: "nvidia"
      log-opts:
        max-file: "5"
        max-size: "10m"
      storage-driver: "{{storage_driver_lo}}"
    storage_opt:
      devicemapper:
        storage-opts:
        - "dm.thinpooldev=/dev/mapper/{{docker_vg}}-thinpool"
        - "dm.use_deferred_removal=true"
        - "dm.use_deferred_deletion=true"
      overlay2:
        storage-opts:
        - "overlay2.override_kernel_check=true"
  shell: echo '{{docker_daemon | combine( storage_opt[storage_driver_lo] ) | to_nice_json}}' > /etc/docker/daemon.json

#- name: 删除docker启动项
#  lineinfile:
#    path: /usr/lib/systemd/system/docker.service
#    state: absent
#    regexp: '^ExecStartPost=/usr/bin/docker-compose.*chartmuseum'

- name: 修改冲突监听
  shell: sed -i 's/-H fd:\/\///g' /usr/lib/systemd/system/docker.service

- name: 刷新配置文件
  shell: systemctl daemon-reload

- name: 启动docker
  service: name=docker state=started enabled=yes